name: Android Release Metadata
on:
  workflow_dispatch: # Manual trigger

jobs:
  android-release-metadata:
    name: Upload Google Play metadata
    runs-on: codeberg-tiny
    container:
      image: runmymind/docker-android-sdk:latest
    environment: production
    steps:
      - name: Checkout sources
        # TODO: use shallow (and sparse?) checkout
        uses: actions/checkout@v4

#      - name: Parallel submodules checkout
#        shell: bash
#        run: git submodule update --depth 1 --init --recursive --jobs=$(($(nproc) * 20))

      - name: Restore release keys
        shell: bash
        run: |
          echo "$PRIVATE_H" | base64 -d > private.h
          echo "$GOOGLE_PLAY_JSON" | base64 -d > android/app/google-play.json
        env:
          PRIVATE_H: ${{ secrets.PRIVATE_H }}
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}

      - name: Upload
        shell: bash
        run: ./gradlew publishGoogleReleaseListing
        working-directory: android
        timeout-minutes: 5
