name: Android Release Metadata
on:
  workflow_dispatch: # Manual trigger

jobs:
  android-release-metadata:
    name: Upload Google Play metadata
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            android
            tools/python/check_store_metadata.py

      - name: Restore release keys
        shell: bash
        run: |
          echo "$GOOGLE_PLAY_JSON" | base64 -d > android/app/google-play.json
        env:
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}

      - name: Upload
        shell: bash
        run: ./gradlew publishGoogleReleaseListing
        working-directory: android
        timeout-minutes: 5
