name: iOS Check metadata
on:
  workflow_dispatch: # Manual trigger
  # TODO: These always fail until we fix how we seed the metadata files
  # pull_request:
  #   paths:
  #     - .forgejo/workflows/ios-check-metadata.yaml  # Run check on self change
  #     - iphone/metadata/**
  #     - tools/python/check_store_metadata.py

jobs:
  ios-check-metadata:
    name: Check app metadata
    runs-on: ubuntu-latest
    steps:
      - name: event
        run: |
          cat <<'EOF'
          ${{ toJSON(github) }}
          EOF
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            iphone/metadata
            tools/python/check_store_metadata.py

      - name: Check metadata
        run: ./tools/python/check_store_metadata.py ios
